<?php

namespace Bitfumes\Blogg\Models;

use Illuminate\Support\Str;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['name', 'slug'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($category) {self::setSlug($category);});
        self::updating(function ($category) {self::setSlug($category);});
    }

    /**
     * @param $category
     */
    public static function setSlug($category)
    {
        $category->slug = Str::slug($category->name);
    }

    public function blogs()
    {
        return $this->hasMany(Blog::class);
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }
}
